BatchnormPruner: Skip running mean/var when tracking_running_stats=False
 When tracking_running_stats is set to false, a batchnorm layer doesn't have running_mean/running_var in weights, thus error occurred:
  File "/usr/local/lib/python3.10/dist-packages/torch_pruning-1.5.1-py3.10.egg/torch_pruning/pruner/function.py", line 207, in prune_out_channels
    AttributeError: 'NoneType' object has no attribute 'data'

 * Ref: https://github.com/pytorch/pytorch/blob/b16ae97ad03a6f376988e505fa23734523d0b4c5/torch/nn/modules/batchnorm.py#L61

Signed-off-by: Isaac Chen <tingyi364@gmail.com>